server:
  port: 9090
  
spring:
  application:
    name: FLYING-CUBE
  banner:
    location: classpath:banner/banner.txt
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
    url: jdbc:p6spy:h2:mem:testdb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500
        query:
          in_clause_parameter_padding: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: classpath:logback/logback-spring.xml    

jwt:
  secret: 1234567890
  expirationDateInMs: 1800000 # half hour
  refreshExpirationDateInMs: 3600000 # hour