drop table if exists tb_deployment CASCADE;

create table tb_deployment
(
    deployment_id   integer generated by default as identity,
    deployment_name varchar(50) not null,
    namespace       varchar(50) not null,
    replicas        integer     not null default 1,
    trigger_stg     varchar(25) not null,
    update_stg      varchar(25) not null,
    created_dt      timestamp,
    updated_dt      timestamp,
    primary key (deployment_id)
);