drop table if exists tb_roles CASCADE;
create table tb_roles
(
    id integer generated by default as identity,
    name varchar(20),
    primary key (id)
);

drop table if exists tb_users CASCADE;
create table tb_users
(
    id integer generated by default as identity,
    username varchar(20),
    password varchar(120),
    email varchar(50),
    primary key (id)
);

drop table if exists tb_user_roles CASCADE;
create table tb_user_roles
(
    user_id integer not null,
    role_id integer not null,
    primary key (user_id, role_id)
);

alter table tb_users
    add constraint uk_tb_user_username unique (username);

alter table tb_users
    add constraint uk_tb_user_email unique (email);

alter table tb_user_roles
    add constraint fk_tb_user_roles_role_id foreign key (role_id) references tb_roles;

alter table tb_user_roles
    add constraint fk_tb_user_roles_user_id foreign key (user_id) references tb_users;


drop table if exists tb_deployment CASCADE;

create table tb_deployment
(
    deployment_id   integer generated by default as identity,
    deployment_name varchar(50) not null,
    namespace       varchar(50) not null,
    replicas        integer     not null default 1,
    trigger_stg     varchar(25) not null,
    update_stg      varchar(25) not null,
    created_dt      timestamp,
    updated_dt      timestamp,
    primary key (deployment_id)
);
